[package]
name = "oto"
version = "0.1.0"
edition = "2024"

[dependencies]
alsa = "0.11.0"
anyhow = "1"
bytemuck = "1.24.0"
clap = { version = "4.5", features = ["derive"] }
directories = "6.0.0"
enclose = "1.2.1"
id3 = "1.16.3"
image = { version = "0.25", default-features = false, features = ["png", "jpeg", "bmp"] }
log = "0.4.29"
ratatui = { version = "0.30.0", default-features = false, features = ["crossterm", "layout-cache", "macros", "unstable-widget-ref"] }
ratatui-image = { git = "https://github.com/ckaznable/ratatui-image.git", rev = "673e0575cfcf140ab7f96fc1976e1b761f494c3d" }
ringbuf = "0.4.8"
simplelog = "0.12.2"
symphonia = { version = "0.5.5", features = ["all-codecs", "opt-simd-sse", "opt-simd-avx"]}
thiserror = "2.0.17"
walkdir = "2.5.0"
strum = { version = "0.27", features = ["derive"] }
lofty = "0.22.4"
rayon = "1.11.0"
souvlaki = { version = "0.8.3", default-features = false, features = ["use_zbus"] }
tempfile = "3.24.0"
gag = "1.0.0"
os_pipe = "1.2.3"
unicode-width = "0.2"
mini-moka = "0.10"
bitcode = "0.6.9"
zstd = "0.13.3"
indexmap = "2.13.0"
rustc-hash = "2.1.1"
itertools = "0.14.0"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
debug = false
rpath = false
